# Generated by Django 2.1.7 on 2019-03-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('sigla_uo', models.CharField(help_text='Ex.: DG-EAD/IFRN', max_length=100, verbose_name='Unidade organizacional')),
                ('link_edital', models.URLField(help_text='Informe o LINK onde está o edital', max_length=300, verbose_name='URL')),
                ('grupo', models.CharField(max_length=200, null=True, verbose_name='Grupo')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('ano', models.PositiveIntegerField(help_text='Digite o ano', verbose_name='Ano')),
                ('periodo', models.PositiveIntegerField(choices=[(1, '1º Período'), (2, '2º Período')], verbose_name='Período letivo')),
                ('data_publicacao', models.DateField(verbose_name='Data de publicação')),
                ('existe_taxa', models.BooleanField(default=False, verbose_name='Existe taxa?')),
                ('valor_taxa', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor da taxa')),
                ('vencimento_boleto', models.DateField(verbose_name='Vencimento do boleto')),
                ('anotacoes', models.TextField(verbose_name='Anotações')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='edital',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.Programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='edital',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.Tipo', verbose_name='Tipo'),
        ),
    ]
