# Generated by Django 2.1.7 on 2019-03-15 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processo_seletivo', '0002_auto_20190315_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.Edital')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('vaga', models.CharField(max_length=100, verbose_name='Vaga')),
                ('numero_vagas', models.PositiveIntegerField(verbose_name='Número de vagas')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.Edital')),
            ],
        ),
    ]
