# Generated by Django 2.1 on 2019-03-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15, verbose_name='Tipo')),
                ('programa', models.CharField(max_length=15, verbose_name='Programa')),
                ('numero', models.CharField(max_length=3, verbose_name='Número')),
                ('siglaUO', models.CharField(max_length=3, verbose_name='Sigla')),
                ('linkEdital', models.CharField(max_length=255, verbose_name='Link')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
    ]
